"""Initial schema

Revision ID: f96d038bdb20
Revises: 
Create Date: 2025-12-23 20:06:56.437328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96d038bdb20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playstore_app_id', sa.String(length=255), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('app_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_id'), 'apps', ['id'], unique=False)
    op.create_index(op.f('ix_apps_playstore_app_id'), 'apps', ['playstore_app_id'], unique=True)
    op.create_table('weekly_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processed', 'failed')", name='chk_batch_status'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'week_start_date', name='uq_app_week_start')
    )
    op.create_index('idx_batch_app_week', 'weekly_batches', ['app_id', 'week_start_date'], unique=False)
    op.create_index('idx_batch_status', 'weekly_batches', ['status'], unique=False)
    op.create_index(op.f('ix_weekly_batches_app_id'), 'weekly_batches', ['app_id'], unique=False)
    op.create_index(op.f('ix_weekly_batches_id'), 'weekly_batches', ['id'], unique=False)
    op.create_table('theme_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_batch_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=255), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('candidate_quotes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_batch_id'], ['weekly_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_theme_batch', 'theme_summaries', ['weekly_batch_id'], unique=False)
    op.create_index(op.f('ix_theme_summaries_id'), 'theme_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_theme_summaries_weekly_batch_id'), 'theme_summaries', ['weekly_batch_id'], unique=False)
    op.create_table('weekly_pulse_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_batch_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('quotes', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_batch_id'], ['weekly_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pulse_batch', 'weekly_pulse_notes', ['weekly_batch_id'], unique=False)
    op.create_index(op.f('ix_weekly_pulse_notes_id'), 'weekly_pulse_notes', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_pulse_notes_weekly_batch_id'), 'weekly_pulse_notes', ['weekly_batch_id'], unique=True)
    op.drop_table('weekly_pulses')
    op.drop_table('analysis_cache')
    op.drop_table('products')
    op.add_column('reviews', sa.Column('app_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('weekly_batch_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('review_date', sa.Date(), nullable=False))
    op.add_column('reviews', sa.Column('review_hash', sa.String(length=64), nullable=False))
    op.alter_column('reviews', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('reviews', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_reviews_date'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_product'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_week'), table_name='reviews')
    op.create_index('idx_review_app_date', 'reviews', ['app_id', 'review_date'], unique=False)
    op.create_index('idx_review_batch', 'reviews', ['weekly_batch_id'], unique=False)
    op.create_index('idx_review_rating', 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_app_id'), 'reviews', ['app_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_review_date'), 'reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_reviews_review_hash'), 'reviews', ['review_hash'], unique=True)
    op.create_index(op.f('ix_reviews_weekly_batch_id'), 'reviews', ['weekly_batch_id'], unique=False)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'weekly_batches', ['weekly_batch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'week_bucket')
    op.drop_column('reviews', 'date')
    op.drop_column('reviews', 'cleaned_text')
    op.drop_column('reviews', 'is_duplicate')
    op.drop_column('reviews', 'product_id')
    op.add_column('subscriptions', sa.Column('app_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('subscriptions', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('subscriptions', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_subscriptions_active'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_product'), table_name='subscriptions')
    op.create_index('idx_subscription_app_email', 'subscriptions', ['app_id', 'email'], unique=False)
    op.create_index(op.f('ix_subscriptions_app_id'), 'subscriptions', ['app_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_email'), 'subscriptions', ['email'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'apps', ['app_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'active')
    op.drop_column('subscriptions', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('product_id', sa.INTEGER(), nullable=False))
    op.add_column('subscriptions', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_email'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_app_id'), table_name='subscriptions')
    op.drop_index('idx_subscription_app_email', table_name='subscriptions')
    op.create_index(op.f('idx_subscriptions_product'), 'subscriptions', ['product_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_active'), 'subscriptions', ['active'], unique=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscriptions', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('subscriptions', 'is_active')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'app_id')
    op.add_column('reviews', sa.Column('product_id', sa.INTEGER(), nullable=False))
    op.add_column('reviews', sa.Column('is_duplicate', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('reviews', sa.Column('cleaned_text', sa.TEXT(), nullable=True))
    op.add_column('reviews', sa.Column('date', sa.DATE(), nullable=False))
    op.add_column('reviews', sa.Column('week_bucket', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_reviews_weekly_batch_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_hash'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_date'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_app_id'), table_name='reviews')
    op.drop_index('idx_review_rating', table_name='reviews')
    op.drop_index('idx_review_batch', table_name='reviews')
    op.drop_index('idx_review_app_date', table_name='reviews')
    op.create_index(op.f('idx_reviews_week'), 'reviews', ['week_bucket'], unique=False)
    op.create_index(op.f('idx_reviews_product'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('idx_reviews_date'), 'reviews', ['date'], unique=False)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('reviews', 'title',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('reviews', 'review_hash')
    op.drop_column('reviews', 'review_date')
    op.drop_column('reviews', 'weekly_batch_id')
    op.drop_column('reviews', 'app_id')
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('playstore_url', sa.TEXT(), nullable=False),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playstore_url')
    )
    op.create_table('analysis_cache',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('week_bucket', sa.TEXT(), nullable=False),
    sa.Column('themes_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'week_bucket')
    )
    op.create_table('weekly_pulses',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('week_start', sa.DATE(), nullable=False),
    sa.Column('week_end', sa.DATE(), nullable=False),
    sa.Column('pulse_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_weekly_pulse_notes_weekly_batch_id'), table_name='weekly_pulse_notes')
    op.drop_index(op.f('ix_weekly_pulse_notes_id'), table_name='weekly_pulse_notes')
    op.drop_index('idx_pulse_batch', table_name='weekly_pulse_notes')
    op.drop_table('weekly_pulse_notes')
    op.drop_index(op.f('ix_theme_summaries_weekly_batch_id'), table_name='theme_summaries')
    op.drop_index(op.f('ix_theme_summaries_id'), table_name='theme_summaries')
    op.drop_index('idx_theme_batch', table_name='theme_summaries')
    op.drop_table('theme_summaries')
    op.drop_index(op.f('ix_weekly_batches_id'), table_name='weekly_batches')
    op.drop_index(op.f('ix_weekly_batches_app_id'), table_name='weekly_batches')
    op.drop_index('idx_batch_status', table_name='weekly_batches')
    op.drop_index('idx_batch_app_week', table_name='weekly_batches')
    op.drop_table('weekly_batches')
    op.drop_index(op.f('ix_apps_playstore_app_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_id'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
